service: lambda-basic-01

# serverless framework는 서울을 지원하지 않기 때문에 ap-northeast-1 (일본, 도쿄) 로 설정
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-1

# lambda에 배포할 함수 명시
functions:
  hello:
    handler: src/handler.generateRandomNumber
